run:
  timeout: 1m
  tests: true

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  revive:
    enable-all-rules: true
    rules:
      - name: cyclomatic
        arguments:
          - 3
      - name: banned-characters
        disabled: true
      - name: file-header
        disabled: true
      - name: argument-limit
        arguments:
          - 3
      - name: function-result-limit
        arguments:
          - 3
      - name: line-length-limit
        arguments:
          - 100
      - name: max-public-structs
        arguments:
          - 3
      - name: function-length
        arguments:
          - 15
          - 0
      - name: cognitive-complexity
        arguments:
          - 7


linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - forcetypeassert
    - gocritic
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 10
