version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: dt
      POSTGRES_PASSWORD: dtp
      POSTGRES_DB: some_db

volumes:
  postgres_data:
    driver: local
