version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PGHOST: db
      HOST: 0.0.0.0

  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: dt
      POSTGRES_PASSWORD: dtp
      POSTGRES_DB: some_db

volumes:
  postgres_data:
    driver: local
